### ISSUE TITLE
[Feat] 메인메뉴 화면 구성

### ISSUE THREAD

**Issue by VesselWheel** [NBCAMP-kiosk-team3/iOS#3]
## To-do
- [x] 메인메뉴 화면 구성을 위한 이슈, 브랜치 생성
- [x] collectionView 화면 UI 구성
- [x] Cell 크기 조정

**Comment by joonBaek12** [comment]
@cantabilano 마크다운 문법에서 - [ ] 는 체크박스를 의미합니다 :) 제가 템플릿에 설명을 해놓는다는걸 깜빡했네요 ㅎㅎ 다음 이슈 파실 때 활용해보시면 좋을 것 같아요!
