### ISSUE TITLE
[Chore] 제출 전 코드 정리

### ISSUE THREAD

**Issue by joonBaek12** [NBCAMP-kiosk-team3/iOS#37]
## To-do

- [x] addTarget 위치 수정
- [x] private 접근제한자로 UI 컴포넌트  캡슐화
- [x] final
- [ ] lazy var 키워드
- [x] 프로토콜 적절한지
- [x] 컨벤션 잘 지켜졌는지
