### ISSUE TITLE
[Feat] 주문내역 UI

### ISSUE THREAD

**Issue by yenny42** [NBCAMP-kiosk-team3/iOS#4]
## To-do

- [x] 내역 리스트(tableView)
- [x] 주문내역 갯수, 총 합계 
- [x] 하단 취소, 결제 버튼
